title: Under the Stars
description: Wairarapa Astronomy
sitename: Under the Stars - Wairarapa Astronomy
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME