# Site settings
title: Under The Stars
email: kaiora@underthestars.co.nz
author: Becky Bateman
description: Astronomy Tours and Stargazing in New Zealand under the Wairarapa's Dark Sky
url: https://www.underthestars.co.nz

# Build settings
permalink: :title/
future: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap