# Site settings
title: Under The Stars
email: kaiora@underthestars.co.nz
author: Becky Bateman
description: Wairarapa Astronomy 
url: https://www.underthestars.co.nz

# Build settings
permalink: :title/
future: true