# Site settings
title: Under The Stars
email: kaiora@underthestars.co.nz
author: Chris Murphy
description: Astronomy Tours and Stargazing in New Zealand under the Wairarapa's Dark Sky
url: https://www.underthestars.co.nz

# Build settings
permalink: :title/
future: true

defaults:
  -
    values:
      theme: "dark"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
